version: '3'
services:
  movies:
    image: krishnapanda02/moviepaytm:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: krishnapanda02/trainpaytm:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: krishnapanda02/dthpaytm:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: krishnapanda02/rechargepaytm:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
